[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#46c45e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#3a3f4b"